name: Deploy

# Trigger the workflow on push and
# pull request events on the production branc
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          port: 22
          password: ${{ secrets.PROD_PASSWORD }}
          script: "cd /var/www/realplayer.fr && ./.scripts/deploy.sh"
